remote_theme: mmistakes/minimal-mistakes
plugins: [jekyll-include-cache]

title: Rajkamal Nailwal
logo: /cropped_image.png
subtitle: "<b>Postdoc (IMFM)</b>"
author:
  name: Rajkamal Nailwal
minimal_mistakes_skin: default   # or "air", "aqua", "dark", etc.
