logo: cropped_image.png 
tittle: <p align="center"><b>Rajkamal Nailwal</b></p> 
description: <p align="center"><b>Postdoc (IMFM)</b></p> 
#email: rajkamal.nailwal@imfm.si 
#show_downloads: true 
theme: jekyll-theme-minimal
